src/Entity/Series.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\SoftDeletableInterface;
use Knp\DoctrineBehaviors\Model\SoftDeletable\SoftDeletableTrait;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use App\Repository\SeriesRepository;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * @ApiResource(attributes={"denormalization_context"={"api_allow_update":true}})
 */
#[ORM\Entity(repositoryClass: SeriesRepository::class)]
class Series implements TimestampableInterface, SoftDeletableInterface, \Stringable
{
    /**
     * Hook SoftDeleteable behavior
     * updates deletedAt field
     */
    use SoftDeletableTrait;
    use TimestampableTrait;

    /**
     * @ApiProperty(identifier=false)
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::INTEGER)]
    private ?int $id = null;

    /**
     * @ApiProperty(identifier=true)
     */
    #[ORM\Column(type: 'uuid', unique: true)]
    #[SerializedName('id')]
    #[Groups(['user:write'])]
    private UuidInterface $uuid;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::TEXT)]
    private string $description = '';

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN)]
    private ?bool $complete = false;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::BOOLEAN)]
    private ?bool $isPublic = true;

    /**
     * @var \Doctrine\Common\Collections\Collection<int, \App\Entity\Event>
     */
    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'series')]
    private Collection $events;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column(type: \Doctrine\DBAL\Types\Types::STRING, length: 50, nullable: true)]
    private ?string $Author = null;

    public function __construct(UuidInterface $uuid = null, string $name = null)
    {
        $this->uuid = $uuid ?: Uuid::uuid4();
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
        $this->setName($name ?: "");
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): UuidInterface
    {
        return $this->uuid;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getComplete(): ?bool
    {
        return $this->complete;
    }

    public function setComplete(bool $complete): self
    {
        $this->complete = $complete;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        if ($description == null) {
            $description = "";
        }
        $this->description = $description;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->addSeries($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            $event->removeSeries($this);
        }

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(?\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getPrettyName(): string
    {
        $author = ($this->getAuthor() != null) ? " - " . $this->getAuthor() . " " : "";
        $date = ($this->getStartDate() != null && $this->getComplete()) ? " (" . $this->getStartDate()->format("Y") . ")" : "";
        return trim($this->getName() . $author . $date);
    }

    public function __toString(): string
    {
        return $this->getPrettyName();
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(?string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }
}

src/Entity/Sermon.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use JMS\Serializer\Annotation as JMS;
use JMS\Serializer\Annotation\SerializedName;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation\Exclude;

use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SermonRepository")
 * @Gedmo\Loggable
 */
class Sermon
{
    /**
     * Hook SoftDeleteable behavior
     * updates deletedAt field
     */
    use SoftDeleteableEntity;
    use TimestampableEntity;
    
    /**
     * @var \Ramsey\Uuid\UuidInterface
     * @JMS\Type("uuid")
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    protected $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $Apm;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Series", inversedBy="sermons")
     * @var Collection
     */
    private $Series;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Reading;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $SecondReading;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="boolean")
     */
    private $corrupt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsPublic;

    /**
     * @ORM\Column(type="text")
     */
    private $Tags;

    /**
     * @ORM\Column(type="text")
     */
    private $PublicComments;

    /**
     * @ORM\Column(type="text")
     */
    private $PrivateComments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Speaker", inversedBy="Sermon")
     */
    private $Speaker;

    public function __construct()
    {
        $this->Series = new ArrayCollection();
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
    }

    public function getId(): ?\Ramsey\Uuid\Uuid
    {
        return $this->id;
    }
 
    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getApm(): ?string
    {
        return $this->Apm;
    }

    public function setId(\Ramsey\Uuid\UuidInterface $id)
    {
        $this->id = $id;
    }
        
    public function setApm($Apm): self
    {
        $this->Apm = $Apm;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getSeries(): Collection
    {
        return $this->Series;
    }

    public function addSeries(Series $series): self
    {
        if (!$this->Series->contains($series)) {
            $this->Series[] = $series;
        }

        return $this;
    }

    public function removeSeries(Series $series): self
    {
        if ($this->Series->contains($series)) {
            $this->Series->removeElement($series);
        }

        return $this;
    }

    public function getReading(): ?string
    {
        return $this->Reading;
    }

    public function setReading(string $Reading): self
    {
        $this->Reading = $Reading;

        return $this;
    }

    public function getSecondReading(): ?string
    {
        return $this->SecondReading;
    }

    public function setSecondReading(string $SecondReading): self
    {
        $this->SecondReading = $SecondReading;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getCorrupt(): ?bool
    {
        return $this->corrupt;
    }

    public function setCorrupt(bool $corrupt): self
    {
        $this->corrupt = $corrupt;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->IsPublic;
    }

    public function setIsPublic(bool $IsPublic): self
    {
        $this->IsPublic = $IsPublic;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->Tags;
    }

    public function setTags(string $Tags): self
    {
        $this->Tags = $Tags;

        return $this;
    }

    public function getPublicComments(): ?string
    {
        return $this->PublicComments;
    }

    public function setPublicComments(string $PublicComments): self
    {
        $this->PublicComments = $PublicComments;

        return $this;
    }

    public function getPrivateComments(): ?string
    {
        return $this->PrivateComments;
    }

    public function setPrivateComments(string $PrivateComments): self
    {
        $this->PrivateComments = $PrivateComments;

        return $this;
    }

    public function getSpeaker(): ?Speaker
    {
        return $this->Speaker;
    }

    public function setSpeaker(?Speaker $speaker): self
    {
        $this->Speaker = $speaker;

        return $this;
    }
}

src/Controller/SermonsController.php
<?php

namespace App\Controller;

use App\Entity\BibleBooks;
use App\Entity\Event;
use App\Entity\Series;
use App\Repository\BibleBooksRepository;
use App\Repository\EventRepository;
use App\Repository\SeriesRepository;
use App\Services\Books\BooksService;
use App\Services\Event\EventSearchService;
use Ramsey\Uuid\Uuid;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/', name: 'sermons_')]
class SermonsController extends AbstractController
{
    private int $itemsPerPage = 16;
    private $searchAllQuery = "*";


    public function __construct(private readonly BooksService $booksService, private readonly EventRepository $eventRepository, private readonly SeriesRepository $seriesRepository)
    {
    }

    /**
     * @param Request $request
     * @param EventSearchService $search
     * @return Responsen
     */
    #[Route(path: '/', name: 'home')]
    public function index(Request $request, EventSearchService $search): Response
    {
        $page = $request->query->get('page', 1);
        $limit = $this->itemsPerPage;

        $searchQuery = trim($request->query->get("q", ""));

        // Fix search query so that empty matches everything
        $searchQuery = ($searchQuery === "") ? $this->searchAllQuery : $searchQuery;

        if ($searchQuery == $this->searchAllQuery) {
            $results = $search->findAllWithPagination($page, $limit);
            $resultsCount = $search->searchMaxPagesItems();

            // Fix search display so that a match all (*) is written as an empty string
            $searchQueryDisplay = ($searchQuery == "*") ? "" : $searchQuery;

            $totalPostsReturned = $results->getIterator()->count();
            $totalPosts = $results->count();
            $iterator = $results->getIterator();
            $startPages = 0 < ($page - 10) ? $page - 10 : 1;
            $maxPages = ceil($resultsCount / $limit);
            $maxPagesToDisplay = $maxPages > $page + 10 ? $page + 10 : $maxPages;
            $thisPage = $page;

            return $this->render('sermons/index.html.twig', [
                'results' => $results,
                'enablePagination' => true,
                'searchQuery' => $searchQueryDisplay,
                'startPages' => $startPages,
                'maxPages' => $maxPagesToDisplay,
                'maxPagesToDisplay' => $maxPages,
                'thisPage' => $thisPage,
            ]);
        } else {
            $results = $search->search($searchQuery);
            $searchQueryDisplay = ($searchQuery == "*") ? "" : $searchQuery;

            return $this->render('sermons/index.html.twig', [
                'results' => $results,
                'searchQuery' => $searchQueryDisplay,
                'showReset' => true,
            ]);
        }
    }

    #[Route(path: '/series/{uuid}', name: 'list_by_series')]
    public function searchField(EventSearchService $search, SeriesRepository $seriesRepository, $uuid): \Symfony\Component\HttpFoundation\Response
    {
        if (!$uuid instanceof Uuid) {
            $uuid = Uuid::fromString($uuid);
        }
        return $this->render('sermons/index.html.twig', [
                    'results' => $search->searchBySeriesUuid($uuid),
                    'series' => $seriesRepository->findOneBy(['uuid' => $uuid]),
                    'searchQuery' => "",
        ]);
    }

    #[Route(path: '/speaker/{value}', name: 'list_by_speaker')]
    public function searchSpeaker(EventSearchService $search, $value): \Symfony\Component\HttpFoundation\Response
    {
        return $this->render('sermons/index.html.twig', [
                    'results' => $search->searchBySpeaker($value),
                    'searchQuery' => "",
        ]);
    }

    #[Route(path: '/listofseries', name: 'list_series')]
    public function ListOfSeries(): \Symfony\Component\HttpFoundation\Response
    {
        $books = $this->booksService->asBibleNameArray();
        $allSeries = $this->seriesRepository->findAll();
        $seriesFromBibleBooks = [];
        $seriesOther = [];
        foreach ($allSeries as $series) {
            if (in_array($series->getName(), $books)) {
                $seriesFromBibleBooks[] = $series;
            } else {
                $seriesOther[] = $series;
            }
        }
        usort($seriesFromBibleBooks, fn (Series $a, Series $b) => $a->getName() <=> $b->getName());
        usort($seriesOther, fn (Series $a, Series $b) => $a->getName() <=> $b->getName());
        $visitingSpeakerSeries = $this->seriesRepository->findOneBy(['name' => "Visiting Speaker"]);
        usort($allSeries, 'strcmp');
        return $this->render('sermons/list_of_series.html.twig', [
                    'books' => $seriesFromBibleBooks,
                    'seriesList' => $seriesOther,
                    'visitingSpeakerSeries' => $visitingSpeakerSeries,
                    'searchQuery' => "",
        ]);
    }

    public function convert_smart_quotes($string)
    {
        $search = [chr(145), chr(146), chr(147), chr(148), chr(151)];

        $replace = ["'", "'", '"', '"', '-'];

        return str_replace($search, $replace, $string);
    }
}

templates/sermons/list_of_series.html.twig
{% extends 'base.html.twig' %}

{% set breadcrumbs = {
    "wecmk_public_home": "Home",
    "members_area_home": "Members Area",
    "sermons_home": "Sermons"
} %}

{% block title %}Sermons{% endblock %}

{% block header_right %}
    <form name="search" class="header-search__form" method="get" action="{{ path('sermons_home') }}">
        <div class="input-group mb-3 header-search" class="">
            <input type="text" class="form-control" name="q" placeholder="Search all sermons" aria-label="search sermons" value="{{ searchQuery }}">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
    </form>
{% endblock %}

{% block content %} 
    <div class="container sermons-navigation-container">
        <div class="d-block d-md-none">
            <div class="flash-message alert alert-info container" role="alert">
                To download or stream, please scroll to the right <span
                    class="glyphicon glyphicon-circle-arrow-right"></span>
            </div>
        </div>
        <div class="btn-group-lg" role="group" aria-label="...">
            <div class="btn-group" role="group">
                <a type="btn btn-secondary" class="btn btn-secondary" href="{% if mainPage is defined %}{{ path('search_all') }}{% else %}{{ path('sermons_home') }}{% endif %}">
                    Back to Sermons
                </a>
            </div>
        </div>
    </div>
    <div class="container">
        <h1>Current/ongoing series</h1>
        <div class="row">
            <div class="col-6">
                <h3>Series by Bible books:</h3>
                {% for book in books %}
                    {% if not book.complete %}
                        <a href="{{ path('sermons_list_by_series', {'uuid': book.Uuid }) }}">{{ book.prettyName }}</a>
                        <br />
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-6">
                <h3>Other series:</h3>
                {% for key,series in seriesList %}
                    {% if series is not empty and not series.complete %}
                        <a href="{{ path("sermons_list_by_series", { 'uuid': series.uuid }) }}">{{ series.PrettyName }}</a>
                        <br />
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <h1>Completed series</h1>
        <div class="row">
            <div class="col-6">
                <h3>Series by Bible books:</h3>
                {% for book in books %}
                    {% if book.complete %}
                        <a href="{{ path('sermons_list_by_series', {'uuid': book.Uuid }) }}">{{ book.prettyName }}</a>
                        <br />
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-6">
                <h3>Other series:</h3>
                {% for key,series in seriesList %}
                    {% if series is not empty and series.complete %}
                        <a href="{{ path("sermons_list_by_series", { 'uuid': series.uuid }) }}">{{ series.PrettyName }}</a>
                        <br />
                    {% endif %}
                {% endfor %}
            </div>

            <div class="col-6">
                <h3>Search by Speaker:</h3>
                <a href="{{ path('sermons_list_by_speaker', {'value': 'Farkhad Makhmudov'}) }}">Farkhad Makhmudov</a><br>
                <a href="{{ path('sermons_list_by_speaker', {'value': 'Roger March'}) }}">Roger March</a><br>
                <a href="{{ path('sermons_list_by_speaker', {'value': 'Roy Moffatt'}) }}">Roy Moffatt</a><br>
                <a href="{{ path('sermons_list_by_speaker', {'value': 'Derek Sparrow'}) }}">Derek Sparrow</a><br>
                <a href="{{ path("sermons_list_by_series", { 'uuid': visitingSpeakerSeries.uuid }) }}">{{ visitingSpeakerSeries.Name }}</a>

            </div>
        </div>
    </div>

{% endblock %}